# Generated by Django 6.0.5 on 2026-05-28 07:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('cloture', 'Clôturé')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice budgétaire',
                'verbose_name_plural': 'Exercices budgétaires',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nature', models.CharField(max_length=10)),
                ('libelle_nature', models.CharField(max_length=255)),
                ('montant_initial', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'ordering': ['code_nature'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Séquence',
                'verbose_name_plural': 'Séquences',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('directeur_drh', 'Directeur DRH'), ('chef_service', 'Chef de service'), ('assistante_drh', 'Assistante DRH'), ('lecteur', 'Lecteur')], default='lecteur', max_length=20)),
                ('nom_complet', models.CharField(blank=True, max_length=150)),
                ('must_change_password', models.BooleanField(default=False, help_text="Si vrai, l'utilisateur est forcé de changer son mot de passe à la prochaine connexion.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('cree', 'Créée'), ('en_etude', 'En étude'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('bc_cree', 'BC créé')], default='cree', max_length=15)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_achat', to='core.exercicebudgetaire')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('direction', models.CharField(default='Direction des Ressources Humaines', max_length=100)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_notification', models.DateField(blank=True, null=True)),
                ('delai_execution_jours', models.PositiveIntegerField(blank=True, help_text="Délai accordé au prestataire pour l'exécution (en jours)", null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('cree', 'Créé'), ('notifie', 'Notifié'), ('en_cours', 'En cours'), ('execute', 'Exécuté'), ('annule', 'Annulé')], db_index=True, default='cree', max_length=10)),
                ('motif_annulation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='core.demandeachat')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='core.exercicebudgetaire')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='core.prestataire')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('DA', "Demande d'achat"), ('BC', 'Bon de commande')], max_length=2)),
                ('entite_id', models.IntegerField()),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('DA.create', 'Création DA'), ('DA.en_etude', 'Mise en étude DA'), ('DA.validate', 'Validation DA'), ('DA.refuse', 'Refus DA'), ('Offre.solliciter', 'Sollicitation prestataire'), ('Offre.saisir', 'Saisie offre reçue'), ('Offre.retenir', 'Rétention offre'), ('Offre.refuser', 'Refus offre'), ('BC.create', 'Création BC'), ('BC.notify', 'Notification BC'), ('BC.start', 'Mise en cours BC'), ('BC.execute', 'Exécution BC'), ('BC.cancel', 'Annulation BC'), ('BC.prolong', 'Prolongation BC'), ('PJ.upload', 'Upload pièce jointe'), ('PJ.delete', 'Suppression pièce jointe'), ('Virement', 'Virement'), ('Tache.create', 'Création tâche'), ('Tache.edit', 'Modification tâche'), ('Tache.delete', 'Suppression tâche'), ('Prestataire.create', 'Création prestataire'), ('Prestataire.delete', 'Suppression prestataire'), ('Exercice.create', 'Création exercice'), ('Exercice.cloture', 'Clôture exercice'), ('Exercice.reconduit', 'Reconduction exercice'), ('User.create', 'Création utilisateur'), ('User.edit', 'Modification utilisateur'), ('User.reset_pwd', 'Réinitialisation MDP'), ('User.delete', 'Suppression utilisateur'), ('Import.excel', 'Import Excel')], max_length=30)),
                ('description', models.TextField()),
                ('entite_type', models.CharField(blank=True, max_length=30)),
                ('entite_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hash_chain', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée du journal',
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ordre', models.IntegerField(default=1)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.boncommande')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ImputationBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='core.boncommande')),
                ('ligne_budgetaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations', to='core.lignebudgetaire')),
            ],
            options={
                'verbose_name': 'Imputation BC',
                'verbose_name_plural': 'Imputations BC',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('entite_type', models.CharField(blank=True, max_length=30)),
                ('entite_id', models.IntegerField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('da', "Demande d'achat"), ('bc', 'Bon de commande'), ('offre', 'Offre prestataire')], max_length=10)),
                ('entite_id', models.IntegerField()),
                ('type_piece', models.CharField(blank=True, choices=[('devis', 'Devis'), ('facture_proforma', 'Facture proforma'), ('bon_commande', 'Bon de commande signé'), ('facture', 'Facture'), ('pv_reception', 'PV de réception'), ('lettre_commande', 'Lettre de commande'), ('offre_technique', 'Offre technique'), ('autre', 'Autre')], default='autre', max_length=25, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='pieces_jointes/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recue', 'Reçue'), ('retenue', 'Retenue'), ('refusee', 'Refusée')], default='en_attente', max_length=10)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_sollicitation', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='core.demandeachat')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prestataire')),
            ],
            options={
                'verbose_name': 'Offre prestataire',
                'ordering': ['date_sollicitation'],
            },
        ),
        migrations.CreateModel(
            name='ProlongationBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_echeance', models.DateField()),
                ('nouvelle_echeance', models.DateField()),
                ('duree_prolongation_jours', models.PositiveIntegerField(default=0)),
                ('motif', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prolongations', to='core.boncommande')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prolongation BC',
                'verbose_name_plural': 'Prolongations BC',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('titre', models.CharField(max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.exercicebudgetaire')),
            ],
            options={
                'verbose_name': 'Tâche budgétaire',
                'verbose_name_plural': 'Tâches budgétaires',
                'ordering': ['numero'],
                'unique_together': {('exercice', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='lignebudgetaire',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.tache'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_achat', to='core.tache'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='core.tache'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('seuil_atteint', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.tache')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirementBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motif', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements', to='core.exercicebudgetaire')),
                ('ligne_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virements_entrants', to='core.lignebudgetaire')),
                ('ligne_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virements_sortants', to='core.lignebudgetaire')),
            ],
            options={
                'verbose_name': 'Virement budgétaire',
                'verbose_name_plural': 'Virements budgétaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['exercice', 'statut', '-created_at'], name='core_boncom_exercic_780bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['tache', 'statut'], name='core_boncom_tache_i_91b0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['prestataire', '-created_at'], name='core_boncom_prestat_edd3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['statut'], name='core_boncom_statut_2650ca_idx'),
        ),
    ]
