# Generated by Django 6.0.5 on 2026-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('cree', 'Créé'), ('notifie', 'Notifié'), ('en_cours', 'En cours'), ('execute', 'Exécuté'), ('annule', 'Annulé')], db_index=True, default='cree', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('cree', 'Créée'), ('en_etude', 'En étude'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('bc_cree', 'BC créé')], default='creee', max_length=15),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['exercice', 'statut', '-created_at'], name='core_boncom_exercic_780bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['tache', 'statut'], name='core_boncom_tache_i_91b0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['prestataire', '-created_at'], name='core_boncom_prestat_edd3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['statut'], name='core_boncom_statut_2650ca_idx'),
        ),
    ]
