# Generated by Django 6.0.5 on 2026-05-18 23:05

from django.db import migrations, models


def fix_statut_creee(apps, schema_editor):
    """Corrige les DA dont le statut vaut 'creee' (bug du default historique)."""
    DemandeAchat = apps.get_model('core', 'DemandeAchat')
    DemandeAchat.objects.filter(statut='creee').update(statut='cree')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boncommande_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('cree', 'Créée'), ('en_etude', 'En étude'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('bc_cree', 'BC créé')], default='cree', max_length=15),
        ),
        migrations.RunPython(fix_statut_creee, noop_reverse),
    ]
