# Generated by Django 6.0.5 on 2026-06-01 10:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercicebudgetaire_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='type_action',
            field=models.CharField(choices=[('DA.create', 'Création DA'), ('DA.en_etude', 'Mise en étude DA'), ('DA.validate', 'Validation DA'), ('DA.refuse', 'Refus DA'), ('Offre.solliciter', 'Sollicitation prestataire'), ('Offre.saisir', 'Saisie offre reçue'), ('Offre.retenir', 'Rétention offre'), ('Offre.refuser', 'Refus offre'), ('BC.create', 'Création BC'), ('BC.notify', 'Notification BC'), ('BC.start', 'Mise en cours BC'), ('BC.execute', 'Exécution BC'), ('BC.cancel', 'Annulation BC'), ('BC.prolong', 'Prolongation BC'), ('PJ.upload', 'Upload pièce jointe'), ('PJ.delete', 'Suppression pièce jointe'), ('Consommation.create', 'Consommation directe'), ('Virement', 'Virement'), ('Tache.create', 'Création tâche'), ('Tache.edit', 'Modification tâche'), ('Tache.delete', 'Suppression tâche'), ('Prestataire.create', 'Création prestataire'), ('Prestataire.delete', 'Suppression prestataire'), ('Exercice.create', 'Création exercice'), ('Exercice.cloture', 'Clôture exercice'), ('Exercice.reconduit', 'Reconduction exercice'), ('User.create', 'Création utilisateur'), ('User.edit', 'Modification utilisateur'), ('User.reset_pwd', 'Réinitialisation MDP'), ('User.delete', 'Suppression utilisateur'), ('Import.excel', 'Import Excel')], max_length=30),
        ),
        migrations.CreateModel(
            name='ConsommationDirecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motif', models.CharField(choices=[('achat_direct', 'Achat direct'), ('assistance_sociale', 'Assistance sociale'), ('urgence', 'Urgence'), ('remboursement', 'Remboursement'), ('correction', 'Correction'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Détails supplémentaires')),
                ('date_consommation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ligne_budgetaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_directes', to='core.lignebudgetaire')),
            ],
            options={
                'verbose_name': 'Consommation directe',
                'verbose_name_plural': 'Consommations directes',
                'ordering': ['-date_consommation', '-created_at'],
            },
        ),
    ]
