# Generated by Django 6.0.5 on 2026-06-02 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journalactivite_type_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepertoireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('titre', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Répertoire tâche',
                'verbose_name_plural': 'Répertoire tâches',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='exercicebudgetaire',
            name='exercice_precedent',
            field=models.ForeignKey(blank=True, help_text="Exercice de l'année précédente (renseigné automatiquement).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_suivants', to='core.exercicebudgetaire'),
        ),
        migrations.AddField(
            model_name='exercicebudgetaire',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Exercice courant — un seul peut être actif (Règle R7).'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='type_action',
            field=models.CharField(choices=[('DA.create', 'Création DA'), ('DA.en_etude', 'Mise en étude DA'), ('DA.validate', 'Validation DA'), ('DA.refuse', 'Refus DA'), ('Offre.solliciter', 'Sollicitation prestataire'), ('Offre.saisir', 'Saisie offre reçue'), ('Offre.retenir', 'Rétention offre'), ('Offre.refuser', 'Refus offre'), ('BC.create', 'Création BC'), ('BC.notify', 'Notification BC'), ('BC.start', 'Mise en cours BC'), ('BC.execute', 'Exécution BC'), ('BC.cancel', 'Annulation BC'), ('BC.prolong', 'Prolongation BC'), ('PJ.upload', 'Upload pièce jointe'), ('PJ.delete', 'Suppression pièce jointe'), ('Consommation.create', 'Consommation directe'), ('Consommation.annuler', 'Annulation consommation directe'), ('Virement.annuler', 'Annulation virement'), ('Virement', 'Virement'), ('Tache.create', 'Création tâche'), ('Tache.edit', 'Modification tâche'), ('Tache.delete', 'Suppression tâche'), ('Prestataire.create', 'Création prestataire'), ('Prestataire.delete', 'Suppression prestataire'), ('Exercice.create', 'Création exercice'), ('Exercice.create_wizard', 'Création exercice (wizard)'), ('Exercice.activer', 'Activation exercice'), ('Exercice.cloture', 'Clôture exercice'), ('Exercice.reconduit', 'Reconduction exercice'), ('User.create', 'Création utilisateur'), ('User.edit', 'Modification utilisateur'), ('User.reset_pwd', 'Réinitialisation MDP'), ('User.delete', 'Suppression utilisateur'), ('Import.excel', 'Import Excel')], max_length=30),
        ),
        migrations.CreateModel(
            name='LogAnnulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('consommation_directe', 'Consommation directe'), ('virement', 'Virement budgétaire'), ('demande_achat', "Demande d'achat"), ('bon_commande', 'Bon de commande')], max_length=30)),
                ('entite_id', models.IntegerField()),
                ('description_avant', models.TextField()),
                ('motif_annulation', models.TextField()),
                ('annule_le', models.DateTimeField(auto_now_add=True)),
                ('annule_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log annulation',
                'verbose_name_plural': 'Logs annulations',
                'ordering': ['-annule_le'],
            },
        ),
        migrations.CreateModel(
            name='RepertoireLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nature', models.CharField(max_length=20)),
                ('libelle_nature', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tache_repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_repertoire', to='core.repertoiretache')),
            ],
            options={
                'verbose_name': 'Répertoire ligne',
                'verbose_name_plural': 'Répertoire lignes',
                'ordering': ['code_nature'],
                'unique_together': {('tache_repertoire', 'code_nature')},
            },
        ),
    ]
