# Generated by Django 6.0.5 on 2026-05-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_demandeachat_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Si vrai, l'utilisateur est force de changer son mot de passe a la prochaine connexion."),
        ),
    ]
