# Generated by Django 6.0.5 on 2026-05-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalactivite',
            name='hash_chain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
