# Generated by Django 6.0.5 on 2026-06-02 — modifiée manuellement
# Étapes :
#  1. Ajouter ligne_budgetaire (nullable)
#  2. Migrer les données (première ligne active de chaque tâche)
#  3. Supprimer tache + modifier les champs existants

import django.db.models.deletion
from django.db import migrations, models


def migrer_da_vers_ligne(apps, schema_editor):
    """
    Pour chaque DA existante, assigner ligne_budgetaire à partir de la
    première ligne active de sa tâche (classée par code_nature).
    """
    DemandeAchat = apps.get_model('core', 'DemandeAchat')
    LigneBudgetaire = apps.get_model('core', 'LigneBudgetaire')

    for da in DemandeAchat.objects.filter(tache__isnull=False).select_related('tache'):
        premiere_ligne = (
            LigneBudgetaire.objects
            .filter(tache=da.tache, actif=True)
            .order_by('code_nature')
            .first()
        )
        if premiere_ligne:
            da.ligne_budgetaire = premiere_ligne
            da.save(update_fields=['ligne_budgetaire'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consommationdirecte_annule_le_and_more'),
    ]

    operations = [
        # Étape 1 : ajouter ligne_budgetaire nullable (garde encore tache)
        migrations.AddField(
            model_name='demandeachat',
            name='ligne_budgetaire',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='demandes_achat',
                to='core.lignebudgetaire',
                verbose_name='Ligne budgétaire concernée',
            ),
        ),

        # Étape 2 : migration de données
        migrations.RunPython(migrer_da_vers_ligne, migrations.RunPython.noop),

        # Étape 3 : supprimer tache
        migrations.RemoveField(
            model_name='demandeachat',
            name='tache',
        ),

        # Étape 4 : modifications des champs existants
        migrations.AlterField(
            model_name='boncommande',
            name='numero',
            field=models.CharField(
                blank=True,
                help_text='Laisser vide pour auto-génération au format BC-DRH-AAAA-XXX',
                max_length=30, unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='reference',
            field=models.CharField(
                blank=True,
                help_text='Laisser vide pour auto-génération au format DA-DRH-AAAA-XXX',
                max_length=30, unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(
                choices=[
                    ('cree', 'Créée'), ('en_etude', 'En étude'), ('validee', 'Validée'),
                    ('refusee', 'Refusée'), ('bc_cree', 'BC créé'), ('annulee', 'Annulée'),
                ],
                default='cree', max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='type_action',
            field=models.CharField(
                choices=[
                    ('DA.create', 'Création DA'), ('DA.en_etude', 'Mise en étude DA'),
                    ('DA.validate', 'Validation DA'), ('DA.refuse', 'Refus DA'),
                    ('DA.edit', 'Modification DA'),
                    ('Offre.solliciter', 'Sollicitation prestataire'),
                    ('Offre.saisir', 'Saisie offre reçue'), ('Offre.retenir', 'Rétention offre'),
                    ('Offre.refuser', 'Refus offre'),
                    ('BC.create', 'Création BC'), ('BC.notify', 'Notification BC'),
                    ('BC.start', 'Mise en cours BC'), ('BC.execute', 'Exécution BC'),
                    ('BC.cancel', 'Annulation BC'), ('BC.prolong', 'Prolongation BC'),
                    ('BC.edit', 'Modification BC'),
                    ('PJ.upload', 'Upload pièce jointe'), ('PJ.delete', 'Suppression pièce jointe'),
                    ('Consommation.create', 'Consommation directe'),
                    ('Consommation.annuler', 'Annulation consommation directe'),
                    ('Virement.annuler', 'Annulation virement'),
                    ('Virement', 'Virement'),
                    ('Tache.create', 'Création tâche'), ('Tache.edit', 'Modification tâche'),
                    ('Tache.delete', 'Suppression tâche'),
                    ('Prestataire.create', 'Création prestataire'),
                    ('Prestataire.edit', 'Modification prestataire'),
                    ('Prestataire.delete', 'Suppression prestataire'),
                    ('Exercice.create', 'Création exercice'),
                    ('Exercice.create_wizard', 'Création exercice (wizard)'),
                    ('Exercice.activer', 'Activation exercice'),
                    ('Exercice.cloture', 'Clôture exercice'),
                    ('Exercice.reconduit', 'Reconduction exercice'),
                    ('User.create', 'Création utilisateur'), ('User.edit', 'Modification utilisateur'),
                    ('User.reset_pwd', 'Réinitialisation MDP'), ('User.delete', 'Suppression utilisateur'),
                    ('User.toggle_actif', 'Activation/désactivation compte'),
                    ('Parametres.seuil', 'Modification seuil alerte'),
                    ('Import.excel', 'Import Excel'),
                ],
                max_length=30,
            ),
        ),
    ]
