# Generated by Django 6.0.5 on 2026-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_format_pad_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='type_action',
            field=models.CharField(choices=[('DA.create', 'Création DA'), ('DA.en_etude', 'Mise en étude DA'), ('DA.validate', 'Validation DA'), ('DA.refuse', 'Refus DA'), ('Offre.solliciter', 'Sollicitation prestataire'), ('Offre.saisir', 'Saisie offre reçue'), ('Offre.retenir', 'Rétention offre'), ('Offre.refuser', 'Refus offre'), ('BC.create', 'Création BC'), ('BC.notify', 'Notification BC'), ('BC.start', 'Mise en cours BC'), ('BC.execute', 'Exécution BC'), ('BC.cancel', 'Annulation BC'), ('BC.prolong', 'Prolongation BC'), ('PJ.upload', 'Upload pièce jointe'), ('PJ.delete', 'Suppression pièce jointe'), ('Consommation.create', 'Consommation directe'), ('Consommation.annuler', 'Annulation consommation directe'), ('Virement.annuler', 'Annulation virement'), ('Virement', 'Virement'), ('Tache.create', 'Création tâche'), ('Tache.edit', 'Modification tâche'), ('Tache.delete', 'Suppression tâche'), ('DA.edit', 'Modification DA'), ('BC.edit', 'Modification BC'), ('Prestataire.create', 'Création prestataire'), ('Prestataire.edit', 'Modification prestataire'), ('Prestataire.delete', 'Suppression prestataire'), ('Exercice.create', 'Création exercice'), ('Exercice.create_wizard', 'Création exercice (wizard)'), ('Exercice.activer', 'Activation exercice'), ('Exercice.cloture', 'Clôture exercice'), ('Exercice.reconduit', 'Reconduction exercice'), ('User.create', 'Création utilisateur'), ('User.edit', 'Modification utilisateur'), ('User.reset_pwd', 'Réinitialisation MDP'), ('User.delete', 'Suppression utilisateur'), ('User.toggle_actif', 'Activation/désactivation compte'), ('Parametres.seuil', 'Modification seuil alerte'), ('Import.excel', 'Import Excel')], max_length=30),
        ),
    ]
