# Generated by Django 6.0.5 on 2026-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_prestation_programmee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['date_emission'], name='idx_bc_date_emission'),
        ),
        migrations.AddIndex(
            model_name='boncommande',
            index=models.Index(fields=['date_echeance'], name='idx_bc_date_echeance'),
        ),
        migrations.AddIndex(
            model_name='consommationdirecte',
            index=models.Index(fields=['ligne_budgetaire', 'est_annule'], name='idx_conso_ligne_annule'),
        ),
        migrations.AddIndex(
            model_name='consommationdirecte',
            index=models.Index(fields=['date_consommation'], name='idx_conso_date'),
        ),
        migrations.AddIndex(
            model_name='demandeachat',
            index=models.Index(fields=['exercice', 'statut'], name='idx_da_exercice_statut'),
        ),
        migrations.AddIndex(
            model_name='demandeachat',
            index=models.Index(fields=['statut'], name='idx_da_statut'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['entite_type', 'entite_id'], name='idx_journal_entite'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['type_action'], name='idx_journal_action'),
        ),
        migrations.AddIndex(
            model_name='prestationprogrammee',
            index=models.Index(fields=['exercice', 'statut'], name='idx_presta_exo_statut'),
        ),
    ]
